create table if not exists public.workspaces (
  id text primary key,
  name text not null,
  slug text not null unique,
  status text not null,
  niche text not null,
  default_language text not null,
  channels jsonb not null default '{}'::jsonb,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create table if not exists public.agents (
  id text primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  name text not null,
  status text not null,
  icp jsonb not null default '{}'::jsonb,
  signals jsonb not null default '{}'::jsonb,
  voice jsonb not null default '{}'::jsonb,
  limits jsonb not null default '{}'::jsonb,
  message_templates jsonb not null default '{}'::jsonb,
  template_weights jsonb,
  linkedin_account_id text,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists agents_workspace_id_idx on public.agents(workspace_id);

create table if not exists public.campaigns (
  id text primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  agent_id text not null references public.agents(id) on delete cascade,
  name text not null,
  status text not null,
  segment text not null,
  search jsonb not null default '{}'::jsonb,
  sequence jsonb not null default '[]'::jsonb,
  execution jsonb,
  settings jsonb,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists campaigns_workspace_id_idx on public.campaigns(workspace_id);
create index if not exists campaigns_agent_id_idx on public.campaigns(agent_id);

create table if not exists public.leads (
  id text primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  campaign_id text not null references public.campaigns(id) on delete cascade,
  provider_id text not null unique,
  name text not null,
  headline text not null default '',
  company text not null default '',
  location text not null default '',
  public_identifier text not null default '',
  network_distance text not null default '',
  profile_picture_url text,
  segment text not null default '',
  language text not null default 'en',
  ai_score integer not null default 0,
  signal text not null default '',
  status text not null,
  current_step integer not null default 0,
  events jsonb not null default '[]'::jsonb,
  template_index integer,
  template_hash text,
  experiment_id text,
  experiment_arm text,
  approved boolean,
  copilot_edits jsonb,
  unipile_chat_id text,
  company_size text,
  industry text,
  company_description text,
  company_linkedin_url text,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists leads_workspace_id_idx on public.leads(workspace_id);
create index if not exists leads_campaign_id_idx on public.leads(campaign_id);
create index if not exists leads_status_idx on public.leads(status);
create index if not exists leads_unipile_chat_id_idx on public.leads(unipile_chat_id);
create index if not exists leads_updated_at_idx on public.leads(updated_at desc);

create table if not exists public.workspace_templates (
  id text primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  name text not null,
  content text not null,
  language text not null,
  type text not null,
  step integer not null default 0,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists workspace_templates_workspace_id_idx on public.workspace_templates(workspace_id);
create index if not exists workspace_templates_workspace_language_step_idx on public.workspace_templates(workspace_id, language, step);

create table if not exists public.contact_lists (
  id text primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  name text not null,
  description text,
  lead_ids text[] not null default '{}',
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists contact_lists_workspace_id_idx on public.contact_lists(workspace_id);

create table if not exists public.discovery_runs (
  id text primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  agent_id text not null,
  started_at timestamptz not null,
  completed_at timestamptz not null,
  status text not null,
  sources jsonb not null default '{}'::jsonb,
  total_discovered integer not null default 0,
  total_duplicates integer not null default 0,
  total_saved integer not null default 0,
  errors jsonb not null default '[]'::jsonb
);

create index if not exists discovery_runs_workspace_started_idx on public.discovery_runs(workspace_id, started_at desc);

create table if not exists public.outreach_runs (
  id bigint generated by default as identity primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  campaign_id text,
  ts timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

create index if not exists outreach_runs_workspace_ts_idx on public.outreach_runs(workspace_id, ts desc);
create index if not exists outreach_runs_campaign_ts_idx on public.outreach_runs(campaign_id, ts desc);

create table if not exists public.webhook_events (
  id bigint generated by default as identity primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  ts timestamptz not null default now(),
  event_type text,
  provider_id text,
  campaign_id text,
  lead_id text,
  payload jsonb not null default '{}'::jsonb
);

create index if not exists webhook_events_workspace_ts_idx on public.webhook_events(workspace_id, ts desc);
create index if not exists webhook_events_provider_idx on public.webhook_events(provider_id);

create table if not exists public.brain_snapshots (
  id text primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  analyzed_at timestamptz not null,
  leads_analyzed integer not null default 0,
  campaigns_analyzed integer not null default 0,
  patterns jsonb not null default '{}'::jsonb,
  recommendations jsonb not null default '[]'::jsonb,
  active_experiment_id text
);

create index if not exists brain_snapshots_workspace_analyzed_idx on public.brain_snapshots(workspace_id, analyzed_at desc);

create table if not exists public.brain_experiments (
  id text primary key,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  campaign_id text not null,
  language text,
  variable text not null,
  hypothesis text not null,
  reasoning text not null,
  control jsonb not null default '{}'::jsonb,
  challenger jsonb not null default '{}'::jsonb,
  status text not null,
  split_ratio numeric not null default 0.5,
  min_sample_per_arm integer not null default 0,
  max_duration_days integer not null default 0,
  control_lead_ids jsonb not null default '[]'::jsonb,
  challenger_lead_ids jsonb not null default '[]'::jsonb,
  mutation_axis text,
  context_snapshot jsonb,
  results jsonb,
  previous_config jsonb,
  proposed_at timestamptz not null,
  approved_at timestamptz,
  started_at timestamptz,
  evaluated_at timestamptz,
  decided_at timestamptz
);

create index if not exists brain_experiments_workspace_idx on public.brain_experiments(workspace_id);
create index if not exists brain_experiments_workspace_status_idx on public.brain_experiments(workspace_id, status);
create index if not exists brain_experiments_campaign_idx on public.brain_experiments(campaign_id);

create unique index if not exists brain_experiments_one_active_per_workspace_idx
  on public.brain_experiments(workspace_id)
  where status in ('approved', 'running');

create table if not exists public.experiment_exposures (
  id text primary key,
  experiment_id text not null references public.brain_experiments(id) on delete cascade,
  workspace_id text not null references public.workspaces(id) on delete cascade,
  campaign_id text not null,
  lead_id text not null,
  provider_id text not null,
  language text not null,
  experiment_arm text not null,
  template_index integer not null,
  template_hash text,
  assigned_at timestamptz not null,
  sent_at timestamptz not null,
  accepted_at timestamptz,
  replied_at timestamptz,
  updated_at timestamptz not null
);

create index if not exists experiment_exposures_experiment_id_idx on public.experiment_exposures(experiment_id);
create index if not exists experiment_exposures_workspace_id_idx on public.experiment_exposures(workspace_id);
create index if not exists experiment_exposures_lead_id_idx on public.experiment_exposures(lead_id);

alter table public.workspaces enable row level security;
alter table public.agents enable row level security;
alter table public.campaigns enable row level security;
alter table public.leads enable row level security;
alter table public.workspace_templates enable row level security;
alter table public.contact_lists enable row level security;
alter table public.discovery_runs enable row level security;
alter table public.outreach_runs enable row level security;
alter table public.webhook_events enable row level security;
alter table public.brain_snapshots enable row level security;
alter table public.brain_experiments enable row level security;
alter table public.experiment_exposures enable row level security;
